<?php

namespace Database\Seeders;

use App\Models\Date;
use App\Models\Department;
use App\Models\Doctordept;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $round = 1;
        $slots = [
            "9:00 - 10:30",
            "10:30 - 12:0",
            "13:30 - 15:00",
            "15:00 - 16:30",
        ];

        $dateStart = date_create('2024-09-30');
        $dateEnd = date_create('2024-10-04');
        $diff = date_diff($dateStart, $dateEnd);
        for ($i = 1; $i <= $diff->days + 1; $i++) {
            $date = date_format($dateStart, "Y-m-d");
            foreach ($slots as $slot) {
                $new_date = new Date;
                $new_date->date = $date;
                $new_date->date_string = strtotime($date);
                $new_date->time = $slot;
                $new_date->round = $round;
                $new_date->save();
                $round = $round + 1;
            }
            $dateStart = date_add($dateStart, date_interval_create_from_date_string("1 days"));
        }

        $dept = new Department(['name' => 'แผนกเครื่องมือแพทย์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกโภชนาการ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์เวชศาสตร์ฟื้นฟู']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องปฏิบัติการ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกเอกซเรย์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกMind Center and Sleep Center (ชั้น 9)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกRegistration']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกการพยาบาลกลาง']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกคลินิกพิเศษนอกโรงพยาบาล']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกจ่ายกลาง']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกฉุกเฉิน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกไตเทียม']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกทันตกรรม(ตึกB)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกเวชระเบียน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศัลยกรรม']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์กุมารเวช']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์จักษุ (ชั้น 8)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์ตรวจสุขภาพ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์ทางเดินอาหารและตับ(ตึกB)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์เบาหวาน และเมตาบอลิก']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์ผิวหนังและศัลยกรรมตกแต่ง (ชั้น 9)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์เลสิค']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์ศัลยกรรมกระดูกและข้อ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์หู คอ จมูก (ชั้น 8)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสถาบันรักษาความปวดและเสริมสร้างความเข้มแข็ง (ชั้น 11)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสถาบันโรคไตและเปลี่ยนไต']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสถาบันหัวใจและหลอดเลือด']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสูตินรีเวช']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องคลอด']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องเด็กอ่อน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องผ่าตัด']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องพักฟื้น']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกห้องส่องกล้องระบบทางเดินอาหาร']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 10']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 14']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 15']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 15(ตึกB)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 16']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 17(ตึกB)']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 6']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยในชั้น 7']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกหอผู้ป่วยวิกฤต ICU - CCU']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกอายุรกรรม']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยบริการเปล']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกคุณภาพ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกจัดซื้อ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกพัฒนาระบบงานทรัพยากรบุคคลและบริหารค่าตอบแทน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกส่งเสริมวัฒนธรรมและสนันสนุนกิจกรรมองค์กร']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสรรหาและพัฒนาบุคลากร']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสวัสดิการและแรงงานสัมพันธ์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสนับสนุนแอปพลิเคชั่นด้านเทคโนโลยีสารสนเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยโครงสร้างพื้นฐานเทคโนโลยีสารสนเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยพัฒนาระบบสนับสนุนการตัดสินใจ']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยสนับสนุนความเป็นเลิศด้านเทคโนโลยี']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยสนับสนุนเทคโนโลยีสารสนเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'บริหารความเสี่ยง']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยการเงินนอก']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยการเงินใน']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยบริการลูกค้าประกันต่างประเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกติดตามหนี้สิน']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยบริการลูกค้าประกันผู้ป่วยนอก']);
        $dept->save();
        $dept = new Department(['name' => 'หน่วยบริการลูกค้าประกันผู้ป่วยใน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกบริหารเงิน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกบัญชีงบประมาณและรายงานทางการเงิน']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกบัญชีปฏิบัติการ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกContact Center']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกการตลาดต่างประเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกการตลาดอาหรับ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกบริหารงานลูกค้าในประเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกลูกค้าสัมพันธ์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกลูกค้าสัมพันธ์ต่างประเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสื่อสารการตลาดต่างประเทศ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสื่อสารแบรนด์และสื่อสารการตลาด']);
        $dept->save();
        $dept = new Department(['name' => '9 Life Health Shop']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกคลังยาและวัสดุ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกจัดซื้อยา-วัสดุและคลังพัสดุ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกเภสัชกรรมบริการ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกเภสัชกรรมบริบาล']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกยานพาหนะ-รักษาความปลอดภัย']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกระบบงานวิศวกรรม']);
        $dept->save();
        $dept = new Department(['name' => 'แผนก Business Strategy and Analytics']);
        $dept->save();
        $dept = new Department(['name' => 'แผนก New Business Strategy']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกนวัตกรรม']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกศูนย์โรงพยาบาลออนไลน์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสำนักงานเลขานุการแพทย์']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกกำกับการปฏิบัติงานและกฏหมาย']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกสำนักผู้อำนวยการ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกธุรการและพัสดุ']);
        $dept->save();
        $dept = new Department(['name' => 'แผนกบริการสถานที่-รักษาความสะอาด']);
        $dept->save();

        $doctor = new Doctordept(['name' => 'อายุรกรรม']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'ศัลยกรรม']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'สูตินรีเวช']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'กุมารเวช']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'MED']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Anes']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'ARI']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Cardio']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Check up']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Dent']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'ENT']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'ER']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'EYE']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'EYE Lasik']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'GI']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Mind center']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Neuro']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'OBS']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Ortho']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'PED']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Pain Center']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Reheb']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Skin']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Surg']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Surg ประสาท']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Wellness']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'X-ray']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'แพทย์แผนจีน']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'KT']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'DM']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'CCU']);
        $doctor->save();
        $doctor = new Doctordept(['name' => 'Chest']);
        $doctor->save();
    }
}
